### ISSUE TITLE
How to use this library

### ISSUE THREAD

**Issue by karmamaster** [torus/Lua-Objective-C-Bridge#6]
Hello,
I read the readme.txt but I can not firgure out how to use this library to call functions from a lua file. Can you help me?

**Comment by karmamaster** [comment]
Hello,
I want to use this within "theos project" which will be build by "make package" on command line but not in Xcode. Can you help me to add this library in theos project?

**Comment by torus** [comment]
I've never used Theos, sorry.

But essentially, you can use this library by just adding LuaBridge.h, LuaBridge.m and LuaBridgeInternal.h 
as well as the entire Lua source code to your project.

**Comment by karmamaster** [comment]
yeah i will try it and be back with the result, thanks.

**Comment by karmamaster** [comment]
Hello,
I have tried to run the file.lua but I countered this error:  not a precompiled chunk. Do you have any idea? 

Thanks

**Comment by torus** [comment]
Is the file.lua pre-compiled?
If you compiled the Lua script on Mac/PC and tried to load on an iOS device, that error may show up.

**Comment by karmamaster** [comment]
Yeah it is compiled, is there anyway I can load this compiled library in lua code?

**Comment by torus** [comment]
Lua's byte code is platform-dependent. So, you need to compile the script on the target device. You can build a luac (Lua compiler) for your iOS device and compile the script on that device.

But it's a bit tedious to do. I recommend loading the script source code on run-time, instead of pre-compiled byte code.
